#!/bin/bash
#
# Lints all code with various linters.

set -eo pipefail

eslint --fix "./"
terraform fmt -recursive "./"

# shellcheck disable=2046
yamllint $(find . -type f -and \( -iname '*.yml' -or -iname '*.yaml' \) -and ! -iwholename '*node_modules*') 2>&1
